"""
HotPlex Python Client

A Python client library for interacting with HotPlex Gateway via AEP v1 protocol.
"""

__version__ = "1.52.0"
__author__ = "HotPlex Team"

# 导出公共 API
from hotplex_client.client import HotPlexClient
from hotplex_client.types import (
    WorkerType,
    SessionState,
    Priority,
    ControlAction,
    Envelope,
    Event,
    InitData,
    InputData,
    MessageData,
    MessageDeltaData,
    MessageStartData,
    MessageEndData,
    ToolCallData,
    ToolResultData,
    PermissionRequestData,
    PermissionResponseData,
    StateData,
    DoneData,
    ErrorData,
    ControlData,
    ErrorCode,
    FileLocation,
    FileDiff,
    ReasoningData,
    StepData,
    RawData,
    DoneStats,
    PongData,
    QuestionOption,
    Question,
    QuestionRequestData,
    QuestionResponseData,
    ElicitationRequestData,
    ElicitationResponseData,
    ContextCategory,
    ContextSkillInfo,
    ContextUsageData,
    SkillsListData,
    SkillEntry,
    MCPStatusData,
    MCPServerInfo,
    WorkerCommandData,
    ToolUpdateData,
    PlanData,
    PlanItem,
    ModeUpdateData,
    InitAckData,
)
from hotplex_client.exceptions import (
    HotPlexError,
    ProtocolError,
    InvalidMessageError,
    VersionMismatchError,
    SessionError,
    SessionNotFoundError,
    SessionTerminatedError,
    SessionExpiredError,
    TransportError,
    ConnectionLostError,
    ReconnectFailedError,
    HeartbeatTimeoutError,
    AuthError,
    UnauthorizedError,
)

__all__ = [
    # Client
    "HotPlexClient",
    # Types
    "WorkerType",
    "SessionState",
    "Priority",
    "ControlAction",
    "Envelope",
    "Event",
    "InitData",
    "InputData",
    "MessageData",
    "MessageDeltaData",
    "MessageStartData",
    "MessageEndData",
    "ToolCallData",
    "ToolResultData",
    "PermissionRequestData",
    "PermissionResponseData",
    "StateData",
    "DoneData",
    "ErrorData",
    "ControlData",
    "ErrorCode",
    "FileLocation",
    "FileDiff",
    "ReasoningData",
    "StepData",
    "RawData",
    "DoneStats",
    "PongData",
    "QuestionOption",
    "Question",
    "QuestionRequestData",
    "QuestionResponseData",
    "ElicitationRequestData",
    "ElicitationResponseData",
    "ContextCategory",
    "ContextSkillInfo",
    "ContextUsageData",
    "SkillsListData",
    "SkillEntry",
    "MCPStatusData",
    "MCPServerInfo",
    "WorkerCommandData",
    "ToolUpdateData",
    "PlanData",
    "PlanItem",
    "ModeUpdateData",
    "InitAckData",
    # Exceptions
    "HotPlexError",
    "ProtocolError",
    "InvalidMessageError",
    "VersionMismatchError",
    "SessionError",
    "SessionNotFoundError",
    "SessionTerminatedError",
    "SessionExpiredError",
    "TransportError",
    "ConnectionLostError",
    "ReconnectFailedError",
    "HeartbeatTimeoutError",
    "AuthError",
    "UnauthorizedError",
]
