package onboard

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"strings"
)

type ConfigTemplateOptions struct {
	SlackEnabled        bool
	SlackDMPolicy       string
	SlackGroupPolicy    string
	SlackRequireMention *bool
	SlackAllowFrom      []string

	FeishuEnabled        bool
	FeishuDMPolicy       string
	FeishuGroupPolicy    string
	FeishuRequireMention *bool
	FeishuAllowFrom      []string

	WorkerType string
}

func DefaultConfigYAML() string {
	return BuildConfigYAML(ConfigTemplateOptions{WorkerType: "claude_code"})
}

func BuildConfigYAML(opts ConfigTemplateOptions) string {
	var b strings.Builder

	b.WriteString(`# HotPlex Worker Gateway - Generated Configuration
# Generated by: hotplex onboard
#
# Sensible defaults for both dev and prod. Override via:
#   1. Inheritance: config-dev.yaml / config-prod.yaml (inherits this file)
#   2. Environment variables: HOTPLEX_* (highest priority)
#   3. Secrets provider: JWT secret, admin tokens (never in config files)
#
# Code defaults live in internal/config/config.go:Default().

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# CORE NETWORK
# ─────────────────────────────────────────────────────────────────────────────

gateway:
  addr: ":8888"
  ping_interval: 54s
  pong_timeout: 60s
  write_timeout: 10s
  idle_timeout: 5m
  max_frame_size: 32768
  broadcast_queue_size: 256

`)

	b.WriteString(`admin:
  enabled: true
  addr: ":9999"
  rate_limit_enabled: true
  requests_per_sec: 10
  burst: 20

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# DATA
# ─────────────────────────────────────────────────────────────────────────────

db:
  path: "~/.hotplex/data/hotplex.db"
  wal_mode: true
  busy_timeout: 500ms

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# SECURITY
# ─────────────────────────────────────────────────────────────────────────────

security:
  api_key_header: "X-API-Key"
  tls_enabled: false
  tls_cert_file: "/etc/hotplex/tls/server.crt"
  tls_key_file: "/etc/hotplex/tls/server.key"
  allowed_origins:
    - "*"
  jwt_audience: "hotplex-worker-gateway"

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# SESSION
# ─────────────────────────────────────────────────────────────────────────────

session:
  retention_period: 168h
  gc_scan_interval: 1m
  max_concurrent: 1000
  event_store_enabled: true
  event_store_type: "sqlite"

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# POOL
# ─────────────────────────────────────────────────────────────────────────────

pool:
  min_size: 0
  max_size: 100
  max_idle_per_user: 5
  max_memory_per_user: 3221225472  # 3GB

`)

	workerType := defaultStr(opts.WorkerType, "claude_code")

	fmt.Fprintf(&b, `# ─────────────────────────────────────────────────────────────────────────────
# WORKER
# ─────────────────────────────────────────────────────────────────────────────

worker:
  max_lifetime: 24h
  idle_timeout: 60m
  execution_timeout: 30m
  type: %q

  auto_retry:
    enabled: true
    max_retries: 9
    base_delay: 5s
    max_delay: 120s
    retry_input: "继续"
    notify_user: true

`, workerType)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────────────────────

log:
  level: "info"
  format: "json"

`)

	b.WriteString("# ─────────────────────────────────────────────────────────────────────────────\n")
	b.WriteString("# MESSAGING\n")
	b.WriteString("# ─────────────────────────────────────────────────────────────────────────────\n\n")
	b.WriteString("messaging:\n")

	writePlatformBlock(&b, "slack", platformBlockOpts{
		Enabled:        opts.SlackEnabled,
		DMPolicy:       defaultStr(opts.SlackDMPolicy, "allowlist"),
		GroupPolicy:    defaultStr(opts.SlackGroupPolicy, "allowlist"),
		RequireMention: defaultBool(opts.SlackRequireMention, true),
		AllowFrom:      opts.SlackAllowFrom,
		Extra:          "    socket_mode: true\n    worker_type: \"claude_code\"\n    stt_provider: \"local\"\n    stt_local_cmd: \"python3 scripts/stt_once.py {file}\"\n    stt_local_mode: \"persistent\"\n    stt_local_idle_ttl: 1h\n",
	})

	writePlatformBlock(&b, "feishu", platformBlockOpts{
		Enabled:        opts.FeishuEnabled,
		DMPolicy:       defaultStr(opts.FeishuDMPolicy, "allowlist"),
		GroupPolicy:    defaultStr(opts.FeishuGroupPolicy, "allowlist"),
		RequireMention: defaultBool(opts.FeishuRequireMention, true),
		AllowFrom:      opts.FeishuAllowFrom,
		Extra:          "    worker_type: \"claude_code\"\n    stt_provider: \"feishu+local\"\n    stt_local_mode: \"ephemeral\"\n    stt_local_idle_ttl: 1h\n",
	})

	b.WriteByte('\n')
	return b.String()
}

type platformBlockOpts struct {
	Enabled        bool
	DMPolicy       string
	GroupPolicy    string
	RequireMention bool
	AllowFrom      []string
	Extra          string
}

func writePlatformBlock(b *strings.Builder, name string, o platformBlockOpts) {
	fmt.Fprintf(b, "  %s:\n    enabled: %t\n", name, o.Enabled)
	b.WriteString(o.Extra)
	fmt.Fprintf(b, "    dm_policy: %q\n    group_policy: %q\n    require_mention: %t\n", o.DMPolicy, o.GroupPolicy, o.RequireMention)
	writeStringList(b, "allow_from", o.AllowFrom)
}

func writeStringList(b *strings.Builder, key string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "    %s:\n", key)
	for _, v := range items {
		fmt.Fprintf(b, "      - %s\n", v)
	}
}

func defaultStr(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func defaultBool(p *bool, def bool) bool {
	if p == nil {
		return def
	}
	return *p
}

func GenerateSecret() string {
	b := make([]byte, 48)
	if _, err := rand.Read(b); err != nil {
		panic("crypto/rand.Read failed: " + err.Error())
	}
	return base64.StdEncoding.EncodeToString(b)
}
